import { defineConfig } from 'vitest/config';
import path from 'node:path';

export default defineConfig({
    test: {
        globals: true,
        environment: 'jsdom',
        coverage: {
            provider: 'v8',
            reporter: ['text', 'json', 'html'],
            reportsDirectory: './coverage',
            include: ['packages/**/*.{ts,tsx}', 'apps/**/*.{ts,tsx}'],
            exclude: [
                '**/node_modules/**',
                '**/dist/**',
                '**/coverage/**',
                '**/*.config.*',
                '**/*.d.ts',
                '**/*.test.*',
                '**/*.spec.*',
                '**/test/**',
                '**/tests/**',
                '**/__tests__/**',
                '**/stories/**',
                '**/*.stories.*',
                '**/vitest.config.*',
                '**/vite.config.*',
                '**/postcss.config.*',
                '**/tailwind.config.*',
                '**/tsconfig.*',
                '**/.eslintrc.*',
                '**/eslint.config.*',
                '**/prettier.config.*',
                '**/jest.config.*',
                '**/webpack.config.*',
                '**/rollup.config.*',
                '**/babel.config.*',
                '**/metro.config.*',
                '**/next.config.*',
                '**/remix.config.*',
                '**/svelte.config.*',
                '**/astro.config.*',
                '**/vite.config.*',
                '**/webpack.*',
                '**/rollup.*',
                '**/babel.*',
                '**/metro.*',
                '**/next.*',
                '**/remix.*',
                '**/svelte.*',
                '**/astro.*',
                '**/vite.*',
            ],
        },
    },
    resolve: {
        alias: {
            '@mono-game/shared': path.resolve(__dirname, './packages/shared'),
            '@mono-game/shared-ui': path.resolve(__dirname, './packages/shared-ui'),
            '@mono-game/shared-styles': path.resolve(__dirname, './packages/shared-styles'),
        },
    },
});